# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Estado', models.CharField(choices=[('AB', 'Abierto'), ('PE', 'Pendiente'), ('EP', 'En Proceso'), ('RE', 'Resuelto'), ('CE', 'Cerrado')], max_length=12)),
                ('FechaCreacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
    ]
